dist: xenial

sudo: false

language: python
python: 3.5

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-1.11

env:
  matrix:
    - TOXENV=flake8
    - TOXENV=py35-1.11
    - TOXENV=py35-2.1
    - TOXENV=py35-2.2

install:
  - pip install tox

script:
  - tox
